version: '3'

services:
  todo_database:
    image: mariadb
    container_name: todo_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todoDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=password --execute \"SHOW DATABASES;\""
      # test: "/usr/local/mysql/bin/mysql --user=foo --password=foo --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    ports:
      - 3306:3306
    volumes:
      - todo_database_volume:/var/lib/mysql

  application:
    image: "bentertech/todoapp"
    container_name: todoapp
    environment:
      - spring.datasource.url=jdbc:mariadb://todo_database:3306/todoDatabase
      - spring.datasource.username=user
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - spring.jpa.hibernate.ddl-auto=create-drop
      - spring.jpa.properties.hibernate.jdbc.time_zone=UTC
      - spring.mvc.formate.date-time=yyyy-MM-dd HH:mm:ss
      - todo.cors.allowed.origins=http://localhost:8080
    ports:
      - 8080:8080
    depends_on:
      - todo_database

volumes:
  todo_database_volume:
